packages:
  - 'src'
catalogs:
  prod:
    'nuxt': 3.16.2
    '@nuxtjs/i18n': ^9.5.4
    'vue': ^3.5.14
  ui3:
    '@nuxt/ui': ^3.1.2
    '@iconify-json/heroicons': ^1.2.2
    '@iconify-json/lucide': ^1.2.44
  dev:
    '@nuxt/devtools': ^2.4.1
    'npm-run-all2': ^8.0.2
    'rimraf': ^6.0.1
    'scaffdog': ^4.1.0
  lint:
    'eslint': ^9.27.0
    '@nuxt/eslint-config': ^1.3.1
    'eslint-plugin-vue-scoped-css': ^2.9.0
    'eslint-plugin-vuejs-accessibility': ^2.4.1
    '@intlify/eslint-plugin-vue-i18n': ^4.0.1
    'eslint-plugin-jsonc': ^2.20.1
    'eslint-plugin-yml': ^1.18.0
  test:
    '@vitest/eslint-plugin': ^1.2.0
    '@vue/test-utils': ^2.4.6
    '@nuxt/test-utils': ^3.19.0
    'vitest': ^3.1.3
