packages:
  - 'src'
catalogs:
  prod:
    'nuxt': 4.3.1
    '@nuxtjs/i18n': ^10.2.3
    'vue': ^3.5.28
  ui3:
    '@nuxt/ui': ^4.4.0
    '@iconify-json/heroicons': ^1.2.3
    '@iconify-json/lucide': ^1.2.91
  dev:
    '@nuxt/devtools': ^3.2.1
    'npm-run-all2': ^8.0.4
    'rimraf': ^6.1.3
    'scaffdog': ^4.1.0
  lint:
    'eslint': ^9.39.2
    '@nuxt/eslint-config': ^1.15.1
    'eslint-plugin-vue-scoped-css': ^2.12.0
    'eslint-plugin-vuejs-accessibility': ^2.5.0
    '@intlify/eslint-plugin-vue-i18n': ^4.1.1
    'eslint-plugin-jsonc': ^3.0.0
    'eslint-plugin-yml': ^3.2.0
  test:
    '@vitest/eslint-plugin': ^1.6.9
    '@vue/test-utils': ^2.4.6
    '@nuxt/test-utils': ^3.23.0
    'vitest': ^4.0.18
