packages:
  - 'src'
catalogs:
  prod:
    'nuxt': 4.3.0
    '@nuxtjs/i18n': ^10.2.3
    'vue': ^3.5.27
  ui3:
    '@nuxt/ui': ^4.4.0
    '@iconify-json/heroicons': ^1.2.3
    '@iconify-json/lucide': ^1.2.89
  dev:
    '@nuxt/devtools': ^3.1.1
    'npm-run-all2': ^8.0.4
    'rimraf': ^6.1.2
    'scaffdog': ^4.1.0
  lint:
    'eslint': ^9.39.2
    '@nuxt/eslint-config': ^1.14.0
    'eslint-plugin-vue-scoped-css': ^2.12.0
    'eslint-plugin-vuejs-accessibility': ^2.4.1
    '@intlify/eslint-plugin-vue-i18n': ^4.1.1
    'eslint-plugin-jsonc': ^2.21.1
    'eslint-plugin-yml': ^3.1.2
  test:
    '@vitest/eslint-plugin': ^1.6.6
    '@vue/test-utils': ^2.4.6
    '@nuxt/test-utils': ^3.23.0
    'vitest': ^4.0.18
