packages:
  - 'src'
catalogs:
  prod:
    'nuxt': 4.0.3
    '@nuxtjs/i18n': ^9.5.6
    'vue': ^3.5.18
  ui3:
    '@nuxt/ui': ^3.3.0
    '@iconify-json/heroicons': ^1.2.2
    '@iconify-json/lucide': ^1.2.62
  dev:
    '@nuxt/devtools': ^2.6.2
    'npm-run-all2': ^8.0.4
    'rimraf': ^6.0.1
    'scaffdog': ^4.1.0
  lint:
    'eslint': ^9.33.0
    '@nuxt/eslint-config': ^1.8.0
    'eslint-plugin-vue-scoped-css': ^2.11.0
    'eslint-plugin-vuejs-accessibility': ^2.4.1
    '@intlify/eslint-plugin-vue-i18n': ^4.1.0
    'eslint-plugin-jsonc': ^2.20.1
    'eslint-plugin-yml': ^1.18.0
  test:
    '@vitest/eslint-plugin': ^1.3.4
    '@vue/test-utils': ^2.4.6
    '@nuxt/test-utils': ^3.19.2
    'vitest': ^3.2.4
