packages:
  - 'src'
catalogs:
  prod:
    'nuxt': 4.2.2
    '@nuxtjs/i18n': ^10.2.1
    'vue': ^3.5.26
  ui3:
    '@nuxt/ui': ^4.3.0
    '@iconify-json/heroicons': ^1.2.3
    '@iconify-json/lucide': ^1.2.82
  dev:
    '@nuxt/devtools': ^3.1.1
    'npm-run-all2': ^8.0.4
    'rimraf': ^6.1.2
    'scaffdog': ^4.1.0
  lint:
    'eslint': ^9.39.2
    '@nuxt/eslint-config': ^1.12.1
    'eslint-plugin-vue-scoped-css': ^2.12.0
    'eslint-plugin-vuejs-accessibility': ^2.4.1
    '@intlify/eslint-plugin-vue-i18n': ^4.1.0
    'eslint-plugin-jsonc': ^2.21.0
    'eslint-plugin-yml': ^1.19.1
  test:
    '@vitest/eslint-plugin': ^1.6.4
    '@vue/test-utils': ^2.4.6
    '@nuxt/test-utils': ^3.21.0
    'vitest': ^3.2.4
