packages:
  - 'src'
catalogs:
  prod:
    'nuxt': 4.1.3
    '@nuxtjs/i18n': ^10.1.0
    'vue': ^3.5.22
  ui3:
    '@nuxt/ui': ^4.0.1
    '@iconify-json/heroicons': ^1.2.3
    '@iconify-json/lucide': ^1.2.68
  dev:
    '@nuxt/devtools': ^2.6.5
    'npm-run-all2': ^8.0.4
    'rimraf': ^6.0.1
    'scaffdog': ^4.1.0
  lint:
    'eslint': ^9.37.0
    '@nuxt/eslint-config': ^1.9.0
    'eslint-plugin-vue-scoped-css': ^2.12.0
    'eslint-plugin-vuejs-accessibility': ^2.4.1
    '@intlify/eslint-plugin-vue-i18n': ^4.1.0
    'eslint-plugin-jsonc': ^2.21.0
    'eslint-plugin-yml': ^1.19.0
  test:
    '@vitest/eslint-plugin': ^1.3.16
    '@vue/test-utils': ^2.4.6
    '@nuxt/test-utils': ^3.19.2
    'vitest': ^3.2.4
