packages:
  - 'src'
catalogs:
  prod:
    'nuxt': 3.16.2
    '@nuxtjs/i18n': ^9.3.1
    'vue': ^3.5.13
  ui2:
    '@nuxt/ui': ^2.21.1
    '@iconify-json/heroicons': ^1.2.2
    '@iconify-json/simple-icons': ^1.2.32
  dev:
    '@nuxt/devtools': ^2.4.0
    '@nuxt/eslint-config': ^1.3.0
    '@nuxt/test-utils': ^3.17.2
    '@vue/test-utils': ^2.4.6
    'eslint': ^9.25.1
    'eslint-plugin-jsonc': ^2.20.0
    'eslint-plugin-vue-scoped-css': ^2.9.0
    'eslint-plugin-vuejs-accessibility': ^2.4.1
    'eslint-plugin-yml': ^1.17.0
    '@vitest/eslint-plugin': ^1.1.43
    'npm-run-all2': ^7.0.2
    'rimraf': ^6.0.1
    'scaffdog': ^4.1.0
    'vitest': ^3.1.2
