name: Pull Request
on:
  issues:
    types:
      - opened

jobs:
  # ref: https://github.com/shinGangan/.github/blob/main/.github/workflows/issue.yml
  set-issue:
    uses: shinGangan/.github/.github/workflows/issue.yml@main
    permissions:
      contents: read
      issues: write
    with:
      number: ${{ github.event.issue.number }}
      title: ${{ github.event.issue.title }}
      assignee: ${{ github.actor }}
      # NOTE: 優先度低いので手動で更新する
      milestone: 'v0.1.0'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      repo: ${{ github.repository }}

  set-label:
    name: Set label
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            /**
             * @typedef {Object} Label
             * @property {string} regex - 検索文字列
             * @property {string} label - ラベル名
             */
            /** @type {Label[]} */
            const labels = [
              { regex: /fix/, label: 'bugs 🐞' },
              { regex: /chore/, label: 'chore 🏠' },
              { regex: /docs/, label: 'docs ✍️' },
              { regex: /refactor/, label: 'refactoring 🧰' },
              { regex: /feat/, label: 'enhancement 🚀' },
            ];

            const issueTitle = context.payload.issue.title;
            const labelsToAdd = [];

            labels.forEach(label => {
              if (label.regex.test(issueTitle)) {
                console.log(`Match: ${label.label}`);
                labelsToAdd.push(label.label);
              }
            });

            if (labelsToAdd.length > 0) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: labelsToAdd
              });
            }
            console.info(`title: ${issueTitle}, labels: ${labelsToAdd.join(',')}`);
